import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "../styles/globals.scss";
import "../styles/reset.scss";

const jost = Jost({ subsets: ["latin"], variable: '--var-jost' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jost.variable}>{children}</body>
    </html>
  );
}
